Implementation of HistoryPage(Epic 6.4)
radicalxdev/kai-platform pull request #60
Opened 2024-06-26 09:41 UTC by pleroux64

# Description
30-Squad has implemented the History Page feature to the Kai Website. This feature adds a new button in the Nav menu that a user can click on to access the history page. This history page contains cards that correspond to instances of when user used a tool like the flashcard or MC generator. These cards are sorted by date, and have information displayed on which tool was used, and how it was used. These cards also have a preview button, which brings up a slide panel with the actual tool data generated from the tool instance card they clicked.

Ticket:

## Type of change
Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. Include screenshot/video if possible.
- [ ] Test A - Use the tools and see if the history page generates a card with all the same information from the tool use.
- [ ] Test B - Use the firestore to assign different dates, and verify the history page sorts by date.
- [ ] Test C - Use the preview button on the Card, to see if a slide panel with all the tool data is displayed with the respective tool 
- [ ] Test D - Use the copy button, and paste it somewhere to see the flashcard or MCQ data.
- [ ] Test E - Use the export button and look at the file to see a table with the tool data, should be different for MCQ and FlashCards

2024-07-01 12:43 UTC, bkb-Git commented
@pleroux64 Looks mostly good, dropped a few comments that would require changes to be made in the codebase and I have a few questions concerning certain aspects of the UI which I'll get to during today's dev workins session.

2024-07-02 01:41 UTC, pleroux64 reviewed
test

2024-07-02 01:41 UTC, pleroux64 commented on frontend/redux/slices/toolsSlice.js
test

2024-07-02 12:02 UTC, bkb-Git requested changes
Please look at the comments and make the requested changes.

2024-07-10 19:50 UTC, bkb-Git requested changes
Left a few comments that need to be resolved

2024-07-10 19:50 UTC, bkb-Git commented on frontend/services/history/transformToolData.jsx
> +    }
Let's abstract this as a default `header || setDefault()`

2024-07-10 19:50 UTC, bkb-Git commented on frontend/utils/DateUtils.js
> +function categorizeDate(creationDate, currentDate) {
Let's stick to a single pattern on how we are creating functions, in this case we use `const categorizeData = () => {}`

2024-07-12 01:58 UTC, pleroux64 commented
@bkb-Git 
Made some changes to make the drawer more dynamic, fixed the redux and added the snapshot, and some other small things

2024-07-15 11:05 UTC, bkb-Git requested changes
Please take a look at some of the comments and make the necessary changes.

2024-07-15 11:05 UTC, bkb-Git commented on functions/controllers/kaiAIController.js
> +    logger.log(`Tool session saved with ID: ${toolSessionRef.id}`);
Let's set a flag called DEBUG in order to display this log when we are debugging, don't need this to log on every instance

2024-07-15 11:05 UTC, bkb-Git commented on frontend/services/toolHistory/transformToolData.jsx
This file shouldn't be under services, it's a util

2024-08-15 11:41 UTC, merged